# Generated by Django 6.0 on 2025-12-15 05:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "weight_per_unit_g",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_department_output", models.BooleanField()),
                (
                    "default_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="board.department",
                    ),
                ),
            ],
        ),
    ]
