# Generated by Django 6.0 on 2025-12-15 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child_units_per_parent_unit",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "child_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components_as_child",
                        to="board.item",
                    ),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components_as_parent",
                        to="board.item",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent_item", "child_item"),
                        name="uniq_itemcomponent_parent_child",
                    )
                ],
            },
        ),
    ]
